ci: change MPI implementation to openmpi
We currently get the pip package `mpich` as MPI implementation.
Recently, we've seen more and more MPI-related issues like

```none
[1786009074.556079] [runnervmvrwv9:4620 :0]        ib_iface.c:1316 UCX  ERROR mana_0: iface 0x55ea1aa0eeb0 failed to create UD QP TX wr:256 sge:6 inl:64 resp:0 RX wr:4096 sge:1 resp:0 failed: Operation not supported
[1786009074.556479] [runnervmvrwv9:4620 :0]      ucp_worker.c:1415 UCX  ERROR uct_iface_open(ud_verbs/mana_0:1) failed: Input/output error
Abort(606225807): Fatal error in internal_Init_thread: Other MPI error, error stack:
internal_Init_thread(71).: MPI_Init_thread(argc=(nil), argv=(nil), required=3, provided=0x7ffdf2bf20d0) failed
MPII_Init_thread(261)....:
MPID_Init(549)...........:
MPIDI_UCX_init_local(234):
MPIDI_UCX_init_worker(86):  ucx function returned with failed status(ucx_init.c 86 MPIDI_UCX_init_worker Input/output error)
```

where MPI fails to init because of a wonky IO error that get's triggered
randomly, but more often if multiple PRs are created at the same time.
Sometimes, it also shows as plain

```none
Error: Process completed with exit code 143.
```

In NDSL, we use the `openmpi` package and seem to have none of the above
issues even with a relatively high load of PRs and merge requests.

This PR thus proses to switch from `mpich` to `openmpi` in an attempt to
stabilize pyFV3 CI runs wrt to the above MPI failures.